export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CREATE_SHOP = "CREATE_SHOP";
export const FETCH_SHOPS = "FETCH_SHOPS";
